name: Build ROS Deb
run-name: ${{ github.actor }} is testing out building Debs from ROS package ðŸš€
on:
  push:
    branches:
      - master
jobs:
  build-ros-deb:
    runs-on: ubuntu-22.04

    steps:
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tree

      - name: Build ROS Deb
        uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: iron
          REPOS_FILE: https://raw.githubusercontent.com/serhiivysotskyi/keyboard_teleop/master/sources.repos
          GITHUB_TOKEN: ${{ secrets.SERHII_GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          output_dir: debs
      
      - name: Upload .deb package
        uses: actions/upload-artifact@v2
        with:
          name: debian-packages
          path: debs/*.deb
